/*
THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF PARALLAX
SOFTWARE CORPORATION ("PARALLAX").  PARALLAX, IN DISTRIBUTING THE CODE TO
END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
COPYRIGHT 1993-1999 PARALLAX SOFTWARE CORPORATION.  ALL RIGHTS RESERVED.
*/

#ifndef _TEXMERGE_H
#define _TEXMERGE_H

int32_t TexMergeInit (int32_t num_cached_textures);
CBitmap *TexMergeGetCachedBitmap (int32_t nBaseTex, int32_t nOvlTex, int32_t nOrient);
void _CDECL_ TexMergeClose (void);
void TexMergeFlush ();
void InitTexMergeShaders ();
int32_t SetupTexMergeShader (int32_t bColorKey, int32_t bColored, int32_t nType);

extern int32_t tmShaderProgs [3]; 

#endif /* _TEXMERGE_H */
