//
// Auto-generated include file [used to be]
// Generated by MAKE from INFERNO.INI settings
//

#ifndef _VERS_ID
#define _VERS_ID

//#ifndef HAVE_CONFIG_H
#	ifndef VERSION
#		define VERSION		"1.13.116"
#	endif
//#endif

#define D2X_NAME		"D2X-XL "

#ifndef D2X_MAJOR
#	define D2X_MAJOR	1
#endif
#ifndef D2X_MINOR
#define D2X_MINOR		13
#endif
#ifndef D2X_MICRO
#define D2X_MICRO		116
#endif

#define VERSION_TYPE		"Full Version"
#define DESCENT_VERSION D2X_NAME VERSION
#define D2X_IVER			(D2XMAJOR * 100000 + D2XMINOR * 1000 + D2XMICRO)

#endif //_VERS_ID
